# Generated by Django 5.0.1 on 2024-10-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='category-images/'),
        ),
    ]
