# Generated by Django 5.0.1 on 2024-10-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_category_images_alter_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermenuitem',
            name='order_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pos.ordermenu'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('images', models.ImageField(upload_to='promotions/')),
                ('applicable_menu', models.ManyToManyField(to='pos.menu')),
            ],
        ),
    ]
