# Generated by Django 5.0.1 on 2024-03-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้ติดต่อ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='หัวข้อ')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('positon', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('offer', models.TextField()),
                ('question_main', models.CharField(max_length=255)),
                ('question_subtopic', models.CharField(max_length=255)),
                ('response_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.surveyresponse')),
            ],
        ),
    ]
