# Generated by Django 5.0.1 on 2024-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_askqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('offer', models.TextField()),
                ('question_main', models.CharField(max_length=255)),
                ('question_subtopic', models.CharField(max_length=255)),
                ('response_value', models.IntegerField()),
            ],
        ),
    ]
