# Generated by Django 5.0.1 on 2024-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_not_complete_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=40, null=True),
        ),
    ]
