# Generated by Django 5.0.1 on 2024-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderproduct_profile_cart_quantity_cart_cartorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
