# Generated by Django 5.0.1 on 2024-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_orderproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='shipping_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
