# Generated by Django 5.0.1 on 2024-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_machine_price_discount_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='machine-slip/'),
        ),
    ]
