# Generated by Django 5.0.1 on 2024-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_reservation_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_rental_price',
            field=models.IntegerField(default=0),
        ),
    ]
